[package]
name = "nullnet-liblogging"
version = "0.1.2"
edition = "2021"
repository = "https://github.com/NullNet-ai/libguard"
license = "MIT"
description = "Logging library for NullNet"
readme = "README.md"

[dependencies]
log = "0.4.25"
syslog = "7.0.0"
chrono = "0.4.39"
once_cell = "1.20.3"