[package]
name = "nullnet-liblogging"
version = "0.2.0"
edition = "2021"
repository = "https://github.com/NullNet-ai/libguard"
license = "MIT"
description = "Logging library for NullNet"
readme = "README.md"
default-run = "simple"

[dependencies]
log = "0.4.26"
syslog = "7.0.0"
chrono = "0.4.39"
once_cell = "1.20.3"
postgres = { version = "0.19.10", features = ["with-chrono-0_4"] }
