[package]
name = "nullnet-libconfmon"
version = "0.1.0"
edition = "2021"
authors= ["Anton Liashkevich <anton.liashkevich.eng@gmail.com>"]
repository = "https://github.com/NullNet-ai/libguard"
license = "MIT"
description = "Configuration monitoring library for NullNet targets"
readne = "README.md"

[dependencies]
tokio = { version = "1.43.0", features = ["full"] }
